---
abstract: 'A flexible engine for running FCGI-based applications'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  Cwd: 0
  ExtUtils::MakeMaker: 6.36
  File::Spec: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0.88
  Test::WWW::Mechanize: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FCGI-Engine
no_index:
  directory:
    - inc
    - t
requires:
  CGI::Simple: 0
  Config::Any: 0
  Declare::Constraints::Simple: 0
  FCGI: 0
  Moose: 0.93
  MooseX::Daemonize: 0.09
  MooseX::Getopt: 0.26
  MooseX::NonMoose: 0
  MooseX::Types::Path::Class: 0
  POSIX: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/fcgi-engine.git
version: 0.21
