---
abstract: 'A flexible engine for running FCGI-based applications'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  Cwd: 0
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
  Test::WWW::Mechanize: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FCGI-Engine
no_index:
  directory:
    - inc
    - t
requires:
  CGI::Simple: 0
  Config::Any: 0
  Declare::Constraints::Simple: 0
  FCGI: 0
  Moose: 0.9
  MooseX::Daemonize: 0.06
  MooseX::Getopt: 0.14
  MooseX::Types::Path::Class: 0
  POSIX: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
