--- 
abstract: A flexible engine for running FCGI-based applications
author: 
  - Stevan Little <stevan@iinteractive.com>
build_requires: 
  Cwd: 0
  File::Spec: 0
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: FCGI-Engine
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI::Simple: 0
  Config::Any: 0
  Declare::Constraints::Simple: 0
  FCGI: 0
  Moose: 0.32
  MooseX::AttributeHelpers: 0.06
  MooseX::Daemonize: 0.05
  MooseX::Getopt: 0.07
  MooseX::Types::Path::Class: 0
  POSIX: 0
tests: t/*.t
version: 0.01
